version: '3'
services:
  api:
    build:
      context: ./api
    ports:
      - "8080:8080"
    container_name: node-api
    volumes:
       - ./api:/usr/src/app/
       - /usr/src/app/node_modules
  dashboard:
    build:
      context: ./dashboard
    ports:
      - "3000:3000"
    container_name: react-ui
    stdin_open: true
    volumes:
       - ./my-app:/app
       - /usr/src/app/my-app/node_modules